/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register/organisation` | `/register/organisation`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register/user` | `/register/user`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/emergency-emails` | `/emergency-emails`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/sos` | `/sos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/admin/dashboard` | `/admin/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/member/dashboard` | `/member/dashboard`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register/organisation` | `/register/organisation`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register/user` | `/register/user`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/emergency-emails` | `/emergency-emails`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/sos` | `/sos`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/admin/dashboard` | `/admin/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/member/dashboard` | `/member/dashboard`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register/organisation${`?${string}` | `#${string}` | ''}` | `/register/organisation${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register/user${`?${string}` | `#${string}` | ''}` | `/register/user${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/emergency-emails${`?${string}` | `#${string}` | ''}` | `/emergency-emails${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/sos${`?${string}` | `#${string}` | ''}` | `/sos${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/admin/dashboard${`?${string}` | `#${string}` | ''}` | `/admin/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/member/dashboard${`?${string}` | `#${string}` | ''}` | `/member/dashboard${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register/organisation` | `/register/organisation`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register/user` | `/register/user`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/emergency-emails` | `/emergency-emails`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/sos` | `/sos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/admin/dashboard` | `/admin/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/member/dashboard` | `/member/dashboard`; params?: Router.UnknownInputParams; };
    }
  }
}
